### ISSUE TITLE
Windows: scan session on PC didn't get the name from Smartphone

### ISSUE THREAD

**Issue by Dtrieb** [fttx/barcode-to-pc-server#105]
If I rename the scan session on my Smartphone the scan session name did't change on the PC Program. #

**Comment by fttx** [comment]
Hi, 

was the app connected while you renamed the scan session?

**Comment by Dtrieb** [comment]
Yes!

**Comment by fttx** [comment]
Ok, i'll investigate

**Comment by Dtrieb** [comment]
Now everything works fine. SORRY! You can close the ticket!

**Comment by fttx** [comment]
Perhaps you did it while it was offline. I'll put a warning dialog that will prevent that

**Comment by fttx** [comment]
fixed on the app side: https://github.com/fttx/barcode-to-pc-app/commit/860fe343e643272931b5430bab261958c4e2cc69
