### ISSUE TITLE
scan time problem

### ISSUE THREAD

**Issue by Bato357** [fttx/barcode-to-pc-server#108]
Hello,
I installed your application and it is very good. For my need and i'm sure anyone else could it be possible to send scan time with the scanned barcode to csv file. There are functions like timestamp date and time but from some reason it gives me text output "unknown". Am i making a mistake using it or there is a bug. I'm using server on windows 10 Pro.
Best regards,

**Comment by fttx** [comment]
Hi,

thank you for your feedback, the csv thing is already on the to-do list: https://github.com/fttx/barcode-to-pc-server/issues/65

The "unknown" output it's due a bug that has been fixed, already: https://github.com/fttx/barcode-to-pc-server/issues/76

If you want, you can use this workaround with the current server version:

- drag a **GREY** box from "Available string components" (barcode.substr or a barcode.replace)
- edit it to read: new Date().toLocaleDateString().

![image](https://user-images.githubusercontent.com/5663423/37833496-a69f3eb2-2eab-11e8-9c25-e19412409e52.png)

If you need the time, you can use the same procedure and type: new Date().toLocaleTimeString()

video: https://imgur.com/a/emNNT

**Comment by Bato357** [comment]
Thank you so much on your reply.

**Comment by Bato357** [comment]
I dont think that you understood my point. Is there a way to get info about real time of scan not the time and date of send function. for example if i scanned something yesterday and i send it to excel today can i get that time and date in excel like i have it on server part and in a mobile app.

**Comment by fttx** [comment]
Yes, it'll be possible in the next version
