### ISSUE TITLE
How to connect to a web app?

### ISSUE THREAD

**Issue by RicardBazn** [fttx/barcode-to-pc-server#121]
Hi I love your app, and it will help me for an small app I'm planning for my friend company. How can i connect the server to my web app? Thanks!

**Comment by fttx** [comment]
Put the cursor on the web page?

**Comment by RicardBazn** [comment]
I try to communicate the barcode pc server with my app. I saw an issue  #61 in which you said with websockets but the link is down. Thanks anyways.

**Comment by fttx** [comment]
This is the WebSocket server implementation of the v2.0.0 version of the server: https://github.com/fttx/barcode-to-pc-server/blob/v2.0.0/main.ts#L202

For the upcoming v3.0.0 version, i changed it quite a bit, see here: https://github.com/fttx/barcode-to-pc-server/blob/master/electron/src/handlers/scans.handler.ts#L28
and here: https://github.com/fttx/barcode-to-pc-server/blob/master/electron/src/handlers/connection.handler.ts#L95
