### ISSUE TITLE
Incorrect time stamp on new scan session

### ISSUE THREAD

**Issue by ZenPacer** [fttx/barcode-to-pc-server#122]
When a new scan session is created on the PC, the timestamp appears to be in am/pm time should be 24 hour time I think.  Refer attached screenshot...
![screenshot time stamp error - 21 jun 18](https://user-images.githubusercontent.com/39733716/41902350-92705d5c-7976-11e8-8e13-03ad4cb7f7ba.png)

**Comment by fttx** [comment]
Fixed in v3
