### ISSUE TITLE
Select imager on android barcode scanner?

### ISSUE THREAD

**Issue by proloog12** [fttx/barcode-to-pc-server#143]
Hi, I would like to try scanning with barcode-to-pc using a Zebra TC70x Android barcode-scanner. Problem however is the app does not seem to find the imager and only seems to allow scanning using the cameras. Is it possible for the app to take input from imagers on Android equipment?

**Comment by fttx** [comment]
Yes, it's possible, you have to open a new scan session and make the scanner type in there.
You also have to set up the scanner so that i'll type the ENTER character after the barcode.
This will work only from v3.0.0+

**Comment by proloog12** [comment]
Thanks a lot for your reply. I will test this and come back to you. Do you have any thoughts on when v3.0.0 will be released?

**Comment by proloog12** [comment]
Hi fttx, I've been testing and configuring now for several hours, but input from the barcode reader does not reach the scan sessions, contrary to input from the cameras. 

De scanner uses DataWedge to associate apps with the barcode reader. Is there a default DataWedge-setup for Barcode-to-PC?

The main issue seems to be the _Intent Action_ (screenprint), maybe combined with the Associated Application-activity. Barcode to pc has 5 possible associations (screenprint), I associated them all. Which Intent Action does DataWedge need to establish the connection?


![image](https://user-images.githubusercontent.com/43344189/45750744-43ee7600-bc10-11e8-8c98-6987c49fbc3c.png)
![image](https://user-images.githubusercontent.com/43344189/45750390-1e14a180-bc0f-11e8-98c3-e54ee2a6d91c.png)

**Comment by fttx** [comment]
It doesn't use intents, the app will read the keystrokes.
Can you setup your scanner to type the barcode?

**Comment by proloog12** [comment]
Thanks for your incredibly fast reply! I disabled _Intent output_ and enabled _Keystroke ouput_.  This offers a sub-option _Basic data formatting_ - in which I tested several combinations, but no communication yet. What am I doing wrong?
![image](https://user-images.githubusercontent.com/43344189/45753553-810b3600-bc19-11e8-9bf2-d089376e03ae.png)
![image](https://user-images.githubusercontent.com/43344189/45753741-01ca3200-bc1a-11e8-8d70-00e7c4695e0b.png)
![image](https://user-images.githubusercontent.com/43344189/45753804-29b99580-bc1a-11e8-8022-d029326bbd63.png)

**Comment by fttx** [comment]
Are you using v3.0.0?
Send me an e-mail at support@barcodetopc.com i'll provide the download

**Comment by proloog12** [comment]
Google Play only offers version 2.0.0. I emailed to support@barcodetopc.com. 

Thanks in advance!
