### ISSUE TITLE
Cannot delete 'orphaned' sessions from server.

### ISSUE THREAD

**Issue by tropicpine** [fttx/barcode-to-pc-server#144]
After archiving my scans to .CSV files I delete the scan sessions from my iPhone as I can find no way to delete the session from the server. 
Over the past year of using BCTPC I have had two incidents of needing to reload my iPhone. Both times a number of sessions are left on the BCTPC server that are not represented on the APP. As there is no function I can find on the server to delete the 'orphaned' sessions I am stuck with them.

-As a work around: How do I manually remove the 'orphaned' sessions?
-As a solution:
   1.) Sync session back to iPhone. Seems the most difficult to implement and messy.
   2.) Provide a delete session function within the server.

If I simply failed to find the delete session function in the server or failed to find this issue in the FAQ let me know.

**Comment by fttx** [comment]
Hi, see #103 

The v3.0.0 will include a button to clear the scan sessions

![image](https://user-images.githubusercontent.com/5663423/45699236-e99ada00-bb69-11e8-9751-565ae1e426fa.png)

**Comment by fttx** [comment]
Related to #184
