### ISSUE TITLE
Overpopulated Scan Sessions Area

### ISSUE THREAD

**Issue by francisco-chernicharo** [fttx/barcode-to-pc-server#146]
Why there isn't a simple way of deleting scan sessions?

With time, it gets way overpopulated and starts being a nuisance. 

Futhermore, a renaming function for scan sessions would be greatly appreciated. 

Thank you in advance.

**Comment by fttx** [comment]
Hi, see #103

The v3.0.0 will include a button to clear the scan sessions

image
