### ISSUE TITLE
Automatically open QR Code url on PC's browser ?

### ISSUE THREAD

**Issue by apcloic** [fttx/barcode-to-pc-server#20]
Hi,

Really good work, congratz !!

We would like to adopt your solution as a replacement to webcodecamjs which is also great but QR code detection is not really good using a webcam while smartphones handle it really well.

So, I think this is not available right now but we will be glad if there could be an option to automatically open scanned QR code URL on PC.
This would avoid the need to open new tab + point mouse cursor in address bar.

Regards,

**Comment by fttx** [comment]
Will work on that
