### ISSUE TITLE
Communicate over USB ?

### ISSUE THREAD

**Issue by apcloic** [fttx/barcode-to-pc-server#21]
It would be also useful if we could pair smartphone to PC over USB instead of network as many office restrict or disable WiFi for security reasons.

**Comment by fttx** [comment]
I do not know if i'll ever implement this feature, i want to keep the app as simple as possible, add more options may confuse the user, and as far as i know iOS does not support any USB communication

**Comment by apcloic** [comment]
@fttx thanks a lot for your reply, good reason indeed, keep it as simple as possible is always a good idea :)
