### ISSUE TITLE
No feedback when changing settings

### ISSUE THREAD

**Issue by samkphx** [fttx/barcode-to-pc-server#240]
Hi,

First I want to say that I love Barcode to PC, but when you change settings on the Barcode to PC server and you press the "Save & Apply" button, there is no feedback that any changes were saved, so I had to go back to the home screen and back to the settings to see if the changes were saved. A way around this could be after the user presses the "Save & Apply" button it could be grayed out, or it could show a success dialogue.

Thanks, Sam

**Comment by fttx** [comment]
Great idea!
