### ISSUE TITLE
In HTTP component, word "times" is interpreted  as cross icon

### ISSUE THREAD

**Issue by dferens** [fttx/barcode-to-pc-server#246]
Hi @fttx ,

The following issue is related only to UI:
<img width="1157" alt="Screen Shot 2020-03-31 at 12 59 47" src="https://user-images.githubusercontent.com/1489339/78014000-f77d0e00-734f-11ea-95c8-6d94d2ce507c.png">

**Comment by fttx** [comment]
Ok, so the request works as expected, right?

**Comment by dferens** [comment]
Yep, we receive correct "TIMESTAMP" query parameter.
