### ISSUE TITLE
Add Ignore duplicated option for BARCODE component

### ISSUE THREAD

**Issue by fttx** [fttx/barcode-to-pc-server#263]

**Comment by fttx** [comment]
Related to #197

**Comment by dominiosc** [comment]
It could be a double option, ignore or ask the user, the question could be, edit existing record or allow duplicate

**Comment by fttx** [comment]
Hi,

now it should be possible by using this Output template: [Detect duplicated.btpt.zip](https://github.com/fttx/barcode-to-pc-server/files/6335772/Detect.duplicated.btpt.zip)

Can you test it? You only need to update the CSV database path:

![image](https://user-images.githubusercontent.com/5663423/115231947-789f7280-a116-11eb-95c1-cdbf3f208ea8.png)

![image](https://user-images.githubusercontent.com/5663423/115231975-805f1700-a116-11eb-8b01-0f294ef7316f.png)

If you don't have a license please contact me at support@barcodetopc.com

**Comment by fttx** [comment]
https://barcodetopc.com/output-template/how-to-detect-duplicated-barcodes/
