### ISSUE TITLE
Can't scan to third-party software

### ISSUE THREAD

**Issue by minhquanssss** [fttx/barcode-to-pc-server#28]
Excel and Notepad work fine. Can't scan barcode to any field in Inflow Inventory software even after changing all the settings available in Barcode to PC server in Windows.

**Comment by fttx** [comment]
![image](https://cloud.githubusercontent.com/assets/5663423/21677466/932b37fa-d33a-11e6-9adb-91ae2d2e7747.png)

I tried to scan into the Item Name/code and it worked.
Try to run Barcode to PC as administrator

**Comment by minhquanssss** [comment]
Thanks. It works!! 

    On Thursday, January 5, 2017 4:33 AM, filippo <notifications@github.com> wrote:
 

 I tried to scan into the Item Name/code and it worked.
Try to run Barcode to PC as administrator—
