### ISSUE TITLE
Unable to build on Windows 10

### ISSUE THREAD

**Issue by ycsin** [fttx/barcode-to-pc-server#285]
Python 2.7.18
Node 10.22.1
npm 6.14.6
VS Build Tools 2019

Failed @ `npm run build`

![1](https://user-images.githubusercontent.com/1563974/95019072-00032800-0696-11eb-8b78-8bc51e35389f.png)
![2](https://user-images.githubusercontent.com/1563974/95019073-01cceb80-0696-11eb-88b6-1c059cb96493.png)
![3](https://user-images.githubusercontent.com/1563974/95019075-02658200-0696-11eb-9a9c-72a305520a37.png)
![4](https://user-images.githubusercontent.com/1563974/95019076-02658200-0696-11eb-9f4a-de3c8ac907e0.png)
![5](https://user-images.githubusercontent.com/1563974/95019077-02fe1880-0696-11eb-9cac-0908309ed86a.png)
![6](https://user-images.githubusercontent.com/1563974/95019078-0396af00-0696-11eb-8ec8-65aba3263259.png)
![7](https://user-images.githubusercontent.com/1563974/95019079-042f4580-0696-11eb-9934-cd2bbe2070c7.png)
[2020-10-04T15_00_54_181Z-debug.log](https://github.com/fttx/barcode-to-pc-server/files/5323441/2020-10-04T15_00_54_181Z-debug.log)

**Comment by fttx** [comment]
Hello,

try using the PowerShell

**Comment by ycsin** [comment]
Compiled successfully by adding `"@types/fs-extra": "8.1.0"` and followed the steps in the `appveyor.yml`, thanks!
