### ISSUE TITLE
server connection issue

### ISSUE THREAD

**Issue by codyfarrow** [fttx/barcode-to-pc-server#33]
I recently tried to use this app as it would help tremendously with my job. The issue is i have the server running in windows, both devices connected to the same network and the app on my android fails to discover the server and connect.

**Comment by fttx** [comment]
Try to add it to windows firewall exceptions and also try to temporarily disable your antivirus

**Comment by codyfarrow** [comment]
I had added it as an exception prior to my first attempt, and tried while anti-virus was disabled with no success.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by fttx** [comment]
There must be something that is blocking the app. Perhaps your access-point uses a different network for wired and wi-fi devices.
Try to download [this app](https://play.google.com/store/apps/details?id=com.overlook.android.fing) and check if it finds your computer.
If you aren't able to see the computer even with Fing app probably the problem is on your network configuration.

**Comment by fttx** [comment]
Are you on android or iOS?

**Comment by tesbreag** [comment]
I finally managed to find an alternate download for the Bonjour SDK, and now have the server and the app installed and launched.  However, the app (Android 5.1) does not find the server (Windows 10).  I have tried disabling the firewall and AV software, which made no difference.  I installed Fing on the Android device, and it was able to see the server's IP address/MAC address.  They are both connected to the same Wi-Fi network.

Any further suggestions?

**Comment by fttx** [comment]
The Bonjour SDK is used only to discover the server IP address, if you already have it you can add the server manually by tapping Select Server in the menu drawer, and then "+" on the up right side.

You don't need to press anything to scan, the supported barcode types list is here: https://github.com/phonegap/phonegap-plugin-barcodescanner#android
