### ISSUE TITLE
Add WooCommerce integration

### ISSUE THREAD

**Issue by fttx** [fttx/barcode-to-pc-server#337]
## Current way
Example output template (Update order status): [example.zip](https://github.com/fttx/barcode-to-pc-server/files/7459235/example.zip)

## New way:

<img width="1136" alt="1" src="https://user-images.githubusercontent.com/5663423/141436718-784dd953-0aee-4607-ab81-022d19bb518a.png">

<img width="1136" alt="2" src="https://user-images.githubusercontent.com/5663423/141436732-8f047008-b804-46c1-940d-0451bb1e3942.png">

Field types: action: select, fields: [{ion-text, ion-text}], auth: ion-text

### Product
- Create product
- Retrieve a product
- Update a product
- Delete a product

### Order
- Create an order
- Retrieve an order
- Update an Order
- Delete an order

Docs: https://woocommerce.github.io/woocommerce-rest-api-docs/

## Example

Output template to Add a product to an order: 

[BARCODE label="Scan the order #"] [BARCODE label="Scan the product ID"] [WOO_COMMERCE action="order_update" key="id" value="barcode[0]", key="line_items" value="[{ id: barcode[1]}]" ]

**Comment by gitschwarz** [comment]
Woocommere has a simple console client. All this features are fast to program. A simple Script and the Run-command from barcode-to-pc are the trick:
Example update stock:
wp --url=url-webshop  --path=path-webshop --user=www-data wc product update ARTICLES_ID --stock_quantity=NEW-STOCK

You find the wp-cli (Debian) under: /usr/share/wordpress/cli/
This can run local or through ssh ...

**Comment by fttx** [comment]
WooCommerce support is now available, could you please test it?

![image](https://user-images.githubusercontent.com/5663423/152645895-2b1941cf-ba6e-4cd6-8bca-6b01d245f5c0.png)

You can pass barcodes in the fields using this syntax: `{{ barcode }}`

Download app: [app-debug.apk.zip](https://github.com/fttx/barcode-to-pc-server/files/8008174/app-debug.apk.zip)
Download server: https://ci.appveyor.com/project/fttx/barcode-to-pc-server/builds/42464378/artifacts (unzip everything in the same folder)

### TODO:

- Test every request
- Add variables injection instructions for the fields option
- Add a link to the official docs next to the fields option (request parameters)
- Create docs that show how to enable the REST API
- Add timeout option
- Add a way to pair using the QR code, or an easy way to share the key and secret between multiple templates and components

**Comment by gitschwarz** [comment]
Sorry - no Windows :-) and the way with bash scripts make more fun and is faster .-)
So: No way to test
Greetings
