### ISSUE TITLE
The app does not input scanned data in electron app in production

### ISSUE THREAD

**Issue by Muhammad-Taif-Khan** [fttx/barcode-to-pc-server#341]
Hi there, i am creating an electron app that needs to receive barcode data using html input element.
The barcode to pc works when my app is in development but it doesn't work when the app is in production.

**Comment by fttx** [comment]
Are you using macOS? Perhaps you need to give the accessibility permissions?
Or if you use Windows you may need to start the server as administrator

**Comment by Muhammad-Taif-Khan** [comment]
I am using windows.

**Comment by Muhammad-Taif-Khan** [comment]
> Are you using macOS? Perhaps you need to give the accessibility permissions? Or if you use Windows you may need to start the server as administrator

Let me try starting the server as administrator.

**Comment by Muhammad-Taif-Khan** [comment]
> Are you using macOS? Perhaps you need to give the accessibility permissions? Or if you use Windows you may need to start the server as administrator

Thank you so much! 
By running as administrator in windows solved the problem.
