### ISSUE TITLE
Automatically update the Window Firewall settings in the installation process

### ISSUE THREAD

**Issue by fttx** [fttx/barcode-to-pc-server#362]
See: nadif.benzaari

Solution 1: https://stackoverflow.com/questions/35103505/add-nsis-firewall-exception-for-both-private-and-public-profiles
Solution 2: https://nsis.sourceforge.io/NSIS_Simple_Firewall_Plugin

**Comment by fttx** [comment]
Ok, this is the installer with the new changes: https://drive.google.com/uc?export=download&id=1rPalC5uh47tL-tNIgCUYMNhYbWloCWLC

Could you please test it? I've also added a command to edit the Windows Firewall settings automatically. Initially, a black command-line window was opening for a few ms just after the installation, but I think I managed to hide it completely now.

Instructions:
1. Download the .zip using the link above
2. Extract everything in the same folder (important)
3. Open the .exe

**Comment by jason-mulree** [comment]
I notice that the firewall rules are added for the Public and Private profiles. I wonder if the rules should be added for the Private profile only? From a security perspective, I am not sure Barcode to PC server should be configured to allow incoming connections when the computer is connected to a public network.
