### ISSUE TITLE
Error when launching version 4.1.0.

### ISSUE THREAD

**Issue by jason-mulree** [fttx/barcode-to-pc-server#370]
The following error is displayed when launching version 4.1.0.

![image](https://user-images.githubusercontent.com/15714467/184472113-51c6f39f-29a5-4e7c-8d9e-f17fc54659a9.png)

This error is not displayed when launching 4.0.0 and this version appears to be working.

**Comment by fttx** [comment]
Thank you for reporting the issue

**Comment by fttx** [comment]
Is your operating system 32 or 64 bit?

**Comment by jason-mulree** [comment]
> Is your operating system 32 or 64 bit?

64-bit.

**Comment by jason-mulree** [comment]
Interestingly, without any changes, and then installing version 4.1.0 again, I notice the application launches! I notice there is a difference between the version 4.1.0 installer I downloaded originally, and the version I downloaded today - has there been any changes to the installer? Perhaps my original download was corrupt?

**Comment by fttx** [comment]
No, it hasn't been modified. Is there a chance you can reproduce the issue? I'm getting in touch with the [@nut](https://github.com/nut-tree/nut.js) developer (the library that seems to cause the problem), but without being able to reproduce the issue it will be hard to fix it.

Could you do these tests for me?

- Delete these files `%appdata%\Local\Temp\*.node`
- Delete the server data file:
![image](https://user-images.githubusercontent.com/5663423/184527691-1822b35e-fba4-4da4-895c-8c80881ab13b.png)
![image](https://user-images.githubusercontent.com/5663423/184527696-28e67900-f76a-4b08-a8b1-3d28dde87294.png)

And finally check if it's related to the v3 -> v4 upgrade by first cleaning the files, installing the [old version](https://github.com/fttx/barcode-to-pc-server/releases/download/v3.18.1/barcode-to-pc-server.offline-installer.zip), and then updating to [v4](https://barcodetopc.com/download/windows).


For reference also another user reported the same issue:
![image](https://user-images.githubusercontent.com/5663423/184527652-cb994e40-108b-4644-b726-dfa6e6e97629.png)

Thank you

**Comment by jason-mulree** [comment]
Hi @fttx,

I can no longer reproduce the issue myself!

The reason for installing Barcode to PC server version 4.1.0 was because I performed a clean install of Windows so when I initially encountered the issue, I did not not have any previous version installed. To troubleshoot I uninstalled version 4.1.0, installed version 4.0.0 which worked, then reinstalled version 4.1.0 which crashed with the error in my initial post. I then uninstalled version 4.1.0, installed version 3.18.1 which worked and installed Bonjour, then version 4.1.0 which crashed. No combination of installed and uninstalling and reinstalling worked so I uninstalled all versions and reported the issue. Mysteriously, the following day or so I tried installing version 4.1.0 again and it worked!

I have since performed another clean install of Windows on the same computer with exactly the same drivers and programs, then downloaded and installed version 4.1.0 and it worked so I purchased the upgrade. I am glad version 4.1.0 is working on my computer but I am at a loss as to explain the error and would have dismissed it as some computer issue if it were not for you indicating that another user is reporting the same issue. Perhaps just get them to wait a day or two and try installing again?

Kind regards,

Jason Mulree

**Comment by jason-mulree** [comment]
Hi @fttx,

I can no longer reproduce the issue myself!

The reason for installing Barcode to PC server version 4.1.0 was because I performed a clean install of Windows so when I initially encountered the issue, I did not not have any previous version installed. To troubleshoot I uninstalled version 4.1.0, installed version 4.0.0 which worked, then reinstalled version 4.1.0 which crashed with the error in my initial post. I then uninstalled version 4.1.0, installed version 3.18.1 which worked and installed Bonjour, then version 4.1.0 which crashed. No combination of installed and uninstalling and reinstalling worked so I uninstalled all versions and reported the issue. Mysteriously, the following day or so I tried installing version 4.1.0 again and it worked!

I have since performed another clean install of Windows on the same computer with exactly the same drivers and programs, then downloaded and installed version 4.1.0 and it worked so I purchased the upgrade. I am glad version 4.1.0 is working on my computer but I am at a loss as to explain the error and would have dismissed it as some computer issue if it were not for you indicating that another user is reporting the same issue. Perhaps just get them to wait a day or two and try installing again?

Kind regards,

Jason Mulree

**Comment by jason-mulree** [comment]
Hi @fttx,

Okay, I can consistently reproduce the error, and things get strange!

On a fresh installation of Windows 10, Barcode to PC server 4.1.0 does not work and displays the error above. However, when I install Office 365, it does work, but when I uninstall Office 365, it does not work!

I am certain that Barcode to PC server 4.1.0 would not rely on Office 365 being installed, would it? Perhaps the Office 365 installer also installs a runtime that Barcode to PC server requires, though I did not see any evidence of this.

This explains why I could not reproduce the issue earlier. I had installed Barcode to PC server 4.1.0 prior to installing Office 365, then later installed Office 365 and from then on Barcode to PC server started working.

I am still trying to understand what the underlying issue might be but wanted to provide this update just in case this triggers something that might assist.

Kind regards,

Jason Mulree

**Comment by jason-mulree** [comment]
Hi @fttx,

Looks like this issue is related to this: https://github.com/nut-tree/nut.js/issues/365

I installed the Microsoft Visual C++ Redistributable (https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) and Barcode to PC server 4.1.0 now works!

Kind regards,

Jason Mulree.

**Comment by fttx** [comment]
Exactly, I've talked to @s1hofmann he's already working to release a patch version of nut.js that will fix the issue 🙂

**Comment by fttx** [comment]
This beta version should fix the issue: https://drive.google.com/file/d/1UwYFQ5FBJwz9RJB8crjOK57a4vPuqn0C/view?usp=sharing
