### ISSUE TITLE
 Push data (collected while offline) to server

### ISSUE THREAD

**Issue by PloughGuy** [fttx/barcode-to-pc-server#55]
By george, I love this app.

But there is just one more thing...

I can collect barcodes while offline, but the only way (that I can find) to force the device app to sync to the server is to restart the server.

Would be nice to have a _Sync to Server_ function in lieu of automatic discovery.

**Comment by fttx** [comment]
Hi, thanks for the feedback!

related to: https://github.com/fttx/barcode-to-pc-app/issues/35
