### ISSUE TITLE
Determine Device That Scanned Barcode

### ISSUE THREAD

**Issue by adamroof** [fttx/barcode-to-pc-server#56]
This may be similar to #53 , but I would like to know which iPhone scanned a barcode, either by entering a setting on the device to add extra string to the end of any scanned barcode, or knowing from the server which device scanned the code.

In example, I would have a setting on an iPhone to add " &loc=9 " to a URL QR Code.
This way anytime our Shipping Department scanned the QR Code on a traveler, we would know our product made it to the shipping door.

If we knew the device at the server, we would know the same thing without needing to enter any settings on the iPhone.

**Comment by fttx** [comment]
You mean something like that?

![image](https://user-images.githubusercontent.com/5663423/29977645-6287c440-8f3e-11e7-900f-fded470510ae.png)

->

![image](https://user-images.githubusercontent.com/5663423/29977725-acb634b6-8f3e-11e7-8fc8-7cdd53203eb8.png)

**Comment by adamroof** [comment]
Yes that could work!
I get error: Property 'editMode' is private and only accessible within class 'StringComponentComponent'
when building however.

**Comment by fttx** [comment]
Fixed, thanks 6b77695c02756e5fbbd9587a8716068bc3e33c91
Anyway, it still doesn't work because i need to make the required changes on the app side in order to send to the server the device name.
In addition to that, the multi-client support isn't bulletproof yet: https://github.com/fttx/barcode-to-pc-server/issues/54

**Comment by fttx** [comment]
Fixed:
* server: fc7474f1ab465cc443a528c89a387adbd44cf8b4
* app: https://github.com/fttx/barcode-to-pc-app/commit/31282a1fef621df483b12608ed278c2d8f7c812b
