### ISSUE TITLE
LF in CSV-file

### ISSUE THREAD

**Issue by JeffZwolle** [fttx/barcode-to-pc-server#66]
I found out that when a CSV-file is created, there are two extra characters added to the beginning of a scanned code.

example:
real code:
5709498213378
result in CSV-file:
LF5709498213378

Realtime strokes is enabled. It strokes the correct code: 5709498213378
“LF” is only seen in the CSV-file

Can this be fixed so that LF are not added anymore?

**Comment by fttx** [comment]
It's a bug of the current stable version, you can fix it by setting the new line character to \r in the server settings

![image](https://user-images.githubusercontent.com/5663423/32699080-179b33fe-c7b0-11e7-9211-b05a0e4cbfeb.png)
 

https://github.com/fttx/barcode-to-pc-server/commit/90acaaea6542ac7914368e804a6e099cf45ecb02
