### ISSUE TITLE
Feature-Request: Server-side running in background

### ISSUE THREAD

**Issue by JeffZwolle** [fttx/barcode-to-pc-server#67]
I just started using Barcode to PC server in the combination Windows with iPhone.
Before I used Kinoni Barcode Reader.

The advantage of Kinoni is that it resides running in the background (server-side).
As soon as the app (on the phone) is started, Kinoni will become active and do the strokes when a barcode is scanned.
At the time Kinoni becomes active (server-side), it only shows a notification-icon in the Windows startbar on the right. So it does not open a programwindow. Programwindows opening are annoying because it meens more mouseclicks.

Can this be made possible in Barcode To PC ?

**Comment by fttx** [comment]
It will be.

duplicated: https://github.com/fttx/barcode-to-pc-server/issues/31
