### ISSUE TITLE
data not coming in excel

### ISSUE THREAD

**Issue by singhainish** [fttx/barcode-to-pc-server#80]
Please suggest how to get data after scanning into an excel sheet. Currently after default installation, it comes inside the application but need is that it come on excel sheet. How is it possible ?

**Comment by fttx** [comment]
Hi,

see here: https://barcodetopc.com/faq.html#scan-to-spreadsheet
and also
![image](https://user-images.githubusercontent.com/5663423/34460632-8282461e-ee14-11e7-9ad7-10cad0b595e1.png)
