### ISSUE TITLE
Shortcut in Typed String

### ISSUE THREAD

**Issue by traponto** [fttx/barcode-to-pc-server#93]
How can I put a shortcut in front of the barcode in order to have the focus on a specific input field?
I tried to insert the <ALT-x> sequence before the barcode but when I send it I get an error from the Pc-server. Also sequences with <Shift> (ex: <Shift> <Home> or <Shift> <End>) do not behave as I hoped (select the text and cancel it with a subsequent <delete> command)

**Comment by fttx** [comment]
Can you show me how did you setup the typed string?
Did you try the TAB component?

**Comment by traponto** [comment]
[StringComponents.zip](https://github.com/fttx/barcode-to-pc-server/files/1671616/StringComponents.zip)

**Comment by fttx** [comment]
Show me the settings page

**Comment by traponto** [comment]
[StringComponents.zip](https://github.com/fttx/barcode-to-pc-server/files/1671629/StringComponents.zip)
Sorry,  I had saved the same image on different files

**Comment by fttx** [comment]
I don't understand what are you trying to achieve.
If you need to move the cursor to the next element you have to put the TAB component

**Comment by traponto** [comment]
In my data entry form I inserted a shortcut <Alt + x> that brings the focus and the cursor to a specific TextBox. I would like the barcode to be inserted in that TextBox without manually placing the data entry cursor

**Comment by fttx** [comment]
Ok, now i understand. At the moment there isn't a way to make it press multiple keys at the same time, but what can you do, is to put more TAB components so that it cycle through your form

**Comment by traponto** [comment]
I do not know how the pc-server application sends characters to the program with active focus, but I have seen that with windows-form applications this is possible through the method SendKeys.Send (String) [https://msdn.microsoft.com/it-it/library/system.windows.forms.sendkeys.send(v=vs.110).aspx]
To specify that any combination of SHIFT, CTRL, and ALT should be held down while several other keys are pressed, enclose the code for those keys in parentheses. For example, to specify to hold down SHIFT while E and C are pressed, use "+(EC)". To specify to hold down SHIFT while E is pressed, followed by C without SHIFT, use "+EC".

**Comment by fttx** [comment]
Yes, of course it is possible, i'll add it in the next version: https://github.com/fttx/barcode-to-pc-server/issues/94
